apiVersion: matrix.paas.io/v1alpha1
kind: AdoptionSources
sources:
  legacyPaas:
    repository: 'D:\XiaK\project\2026\matrix'
    commit: 69336e51f94fa98f6aa278fa4c62382e224dbeaf
    paths:
      - app/service/paas
      - app/ui/src/ui/xiak
    mode: selective-slices
  senatriaFoundation:
    repository: 'D:\XiaK\project\2026\senatria\matrix'
    commit: f51d5ed19fd60e8c4e43500af5e669d67ae4ef7d
    paths:
      - app/service/iam
      - app/service/audit
      - platform/go/foundation
      - platform/go/sdk
      - deploy/compose
    mode: minimal-dependency-extraction
  paasDesign:
    repository: 'D:\XiaK\project\2026\senatria\matrix'
    commit: 338d9b5fcb820120c32265e380c55e5f171cdb75
    paths:
      - docs/paas
    mode: redesign-for-independent-product
