package compose

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"slices"
	"strings"

	paasv1 "github.com/xiak/matrix/api/paas/v1"
)

const (
	ArtifactCatalogAPIVersion = "apphosting.matrix.xiak.com/v1"
	ArtifactCatalogKind       = "LocalArtifactCatalog"
	maximumArtifactCatalog    = 1024 * 1024
	maximumCatalogEntries     = 128
)

// ArtifactCatalog is generated by the installation boundary from
// authenticated release content. Artifact digests are the authority; image
// names and tags deliberately do not enter this contract.
type ArtifactCatalog struct {
	APIVersion string                 `json:"apiVersion"`
	Kind       string                 `json:"kind"`
	Entries    []ArtifactCatalogEntry `json:"entries"`
}

type ArtifactCatalogEntry struct {
	ArtifactDigest string `json:"artifactDigest"`
	ImageID        string `json:"imageId"`
}

// EncodeArtifactCatalog produces the exact representation consumed by the
// worker. Installation persists this content as a restrictive read-only file.
func EncodeArtifactCatalog(catalog ArtifactCatalog) ([]byte, error) {
	if err := ValidateArtifactCatalog(catalog); err != nil {
		return nil, err
	}
	content, err := json.Marshal(catalog)
	if err != nil || len(content) > maximumArtifactCatalog {
		return nil, errors.New("encode local artifact catalog failed")
	}
	return content, nil
}

// DecodeArtifactCatalog accepts only the canonical, strictly versioned
// document so a modified generated file cannot silently change meaning.
func DecodeArtifactCatalog(content []byte) (ArtifactCatalog, error) {
	if len(content) == 0 || len(content) > maximumArtifactCatalog {
		return ArtifactCatalog{}, errors.New("local artifact catalog size is invalid")
	}
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	var catalog ArtifactCatalog
	if err := decoder.Decode(&catalog); err != nil {
		return ArtifactCatalog{}, errors.New("local artifact catalog is invalid")
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return ArtifactCatalog{}, errors.New("local artifact catalog has trailing content")
	}
	canonical, err := EncodeArtifactCatalog(catalog)
	if err != nil || !bytes.Equal(canonical, content) {
		return ArtifactCatalog{}, errors.New("local artifact catalog is not canonical")
	}
	return catalog, nil
}

func ValidateArtifactCatalog(catalog ArtifactCatalog) error {
	if catalog.APIVersion != ArtifactCatalogAPIVersion || catalog.Kind != ArtifactCatalogKind {
		return errors.New("local artifact catalog type is unsupported")
	}
	if len(catalog.Entries) == 0 || len(catalog.Entries) > maximumCatalogEntries {
		return errors.New("local artifact catalog inventory size is invalid")
	}
	previous := ""
	for _, entry := range catalog.Entries {
		if paasv1.ValidateDigest("artifactDigest", entry.ArtifactDigest) != nil ||
			!localImageDigestPattern.MatchString(entry.ImageID) {
			return errors.New("local artifact catalog entry is invalid")
		}
		if previous >= entry.ArtifactDigest {
			return errors.New("local artifact catalog entries are duplicated or not sorted")
		}
		previous = entry.ArtifactDigest
	}
	return nil
}

type imageInspector interface {
	ConfirmExactImage(context.Context, string) error
}

type localImageInspector struct{}

func (localImageInspector) ConfirmExactImage(ctx context.Context, imageID string) error {
	if ctx == nil || !localImageDigestPattern.MatchString(imageID) {
		return errors.New("local image inspection input is invalid")
	}
	var output boundedBuffer
	output.maximum = 1024
	_, err := runDocker(ctx, &output, "image", "inspect", "--format", "{{.Id}}", imageID)
	if err != nil || output.exceeded || strings.TrimSpace(output.String()) != imageID {
		return errors.New("verified local image is unavailable")
	}
	return nil
}

// CatalogArtifactResolver admits only images in the authenticated local
// catalog and rechecks their exact content-addressed Docker identity before
// every compilation. It never uses an artifact locator, tag, registry, pull,
// or build as authority.
type CatalogArtifactResolver struct {
	entries   map[string]string
	ordered   []ArtifactCatalogEntry
	inspector imageInspector
}

func NewCatalogArtifactResolver(catalog ArtifactCatalog) (*CatalogArtifactResolver, error) {
	return newCatalogArtifactResolver(catalog, localImageInspector{})
}

func newCatalogArtifactResolver(
	catalog ArtifactCatalog,
	inspector imageInspector,
) (*CatalogArtifactResolver, error) {
	if err := ValidateArtifactCatalog(catalog); err != nil {
		return nil, err
	}
	if inspector == nil {
		return nil, errors.New("local image inspector is required")
	}
	entries := make(map[string]string, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		entries[entry.ArtifactDigest] = entry.ImageID
	}
	return &CatalogArtifactResolver{
		entries: entries, ordered: slices.Clone(catalog.Entries), inspector: inspector,
	}, nil
}

func (resolver *CatalogArtifactResolver) ResolveVerifiedImage(
	ctx context.Context,
	artifact paasv1.ArtifactRef,
) (VerifiedImage, error) {
	if resolver == nil || resolver.inspector == nil || resolver.entries == nil {
		return VerifiedImage{}, errors.New("local artifact resolver is not configured")
	}
	if ctx == nil {
		return VerifiedImage{}, errors.New("artifact resolution context is required")
	}
	if artifact.Kind != paasv1.ArtifactOCIImage ||
		paasv1.ValidateSafeExternalText("artifact.locator", artifact.Locator, 2048, true) != nil ||
		paasv1.ValidateDigest("artifact.digest", artifact.Digest) != nil {
		return VerifiedImage{}, errors.New("artifact reference is invalid")
	}
	imageID, found := resolver.entries[artifact.Digest]
	if !found {
		return VerifiedImage{}, errors.New("artifact digest is not admitted by the local catalog")
	}
	if err := resolver.inspector.ConfirmExactImage(ctx, imageID); err != nil {
		return VerifiedImage{}, errors.New("artifact image identity cannot be verified")
	}
	return VerifiedImage{ArtifactDigest: artifact.Digest, LocalReference: imageID}, nil
}

// Ready proves that every catalog image is still present by exact immutable
// identity. It is used by the worker's internal readiness endpoint.
func (resolver *CatalogArtifactResolver) Ready(ctx context.Context) error {
	if resolver == nil || resolver.inspector == nil || len(resolver.ordered) == 0 {
		return errors.New("local artifact resolver is not configured")
	}
	if ctx == nil {
		return errors.New("artifact readiness context is required")
	}
	for _, entry := range resolver.ordered {
		if err := resolver.inspector.ConfirmExactImage(ctx, entry.ImageID); err != nil {
			return errors.New("local artifact catalog is not ready")
		}
	}
	return nil
}
