package identityaccess

import (
	"context"
	"errors"
	"net/url"

	auditv1 "github.com/xiak/matrix/api/audit/v1"
	iamv1 "github.com/xiak/matrix/api/iam/v1"
	"github.com/xiak/matrix/app/service/iam/internal/authority"
)

var ErrTOTPEnrollmentNotFound = errors.New("TOTP enrollment was not found")

// The seed was generated by the fixed authority primitive, not caller input.
// This wire content is for local provisioning only, never a redirect or an
// external QR request. Stable IDs distinguish equal login names.
func totpProvisioningURI(account iamv1.AccountID, user iamv1.PrincipalID, seed iamv1.Secret) (iamv1.Secret, error) {
	encoded := seed.CopyBytes()
	defer clear(encoded)
	values := url.Values{"secret": {string(encoded)}, "issuer": {"MATRIX"}, "algorithm": {"SHA1"}, "digits": {"6"}, "period": {"30"}}
	uri := url.URL{Scheme: "otpauth", Host: "totp", Path: "/MATRIX:" + string(account) + ":" + string(user), RawQuery: values.Encode()}
	return iamv1.NewSecret(uri.String())
}

// Enrollment owns a pending seed and its irreversible confirmation, not a
// second identity or a generic command/receipt mechanism.
type TOTPEnrollmentStart struct {
	Attempt             PasswordAttempt
	RequestID, FactorID string
	ExpectedRevision    uint64
	Scope               iamv1.TOTPWrappingScope
	Sealed              authority.SealedTOTPSeed
}

type TOTPEnrollmentStartResult struct {
	Outcome    string               `json:"outcome"`
	Enrollment iamv1.TOTPEnrollment `json:"enrollment"`
}

type MFARecoveryCodeVerifier struct {
	ID                 string `json:"id"`
	VerificationDigest string `json:"verificationDigest"`
}

type TOTPEnrollmentConfirmation struct {
	Attempt                 TOTPAttempt
	VerifiedStep            int64
	BatchID, NotificationID string
	Codes                   []MFARecoveryCodeVerifier
	AuditEvent              auditv1.Event
}

func (service *Authority) totpSession(ctx context.Context, tx Transaction, credential iamv1.Secret) (SessionCredential, error) {
	now, err := transactionTime(ctx, tx)
	if err != nil {
		return SessionCredential{}, err
	}
	subject, err := service.authenticateSession(ctx, tx, credential, now)
	if err != nil {
		return SessionCredential{}, err
	}
	if subject.Subject.Principal.MustChangePassword {
		return SessionCredential{}, ErrForbidden
	}
	return subject, nil
}

func (service *Authority) AuthenticatorState(ctx context.Context, credential iamv1.Secret) (iamv1.AuthenticatorState, error) {
	var result iamv1.AuthenticatorState
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		result, err = tx.ReadAuthenticatorState(ctx, subject.Subject.Session)
		return err
	})
	if err != nil {
		return iamv1.AuthenticatorState{}, err
	}
	if iamv1.ValidateAuthenticatorState(result) != nil {
		return iamv1.AuthenticatorState{}, ErrUnavailable
	}
	return result, nil
}

func (service *Authority) TOTPEnrollment(ctx context.Context, credential iamv1.Secret, id string) (iamv1.TOTPEnrollment, error) {
	return service.readEnrollment(ctx, credential, id, false)
}

func (service *Authority) TOTPEnrollmentByRequest(ctx context.Context, credential iamv1.Secret, requestID string) (iamv1.TOTPEnrollment, error) {
	return service.readEnrollment(ctx, credential, requestID, true)
}

func (service *Authority) readEnrollment(ctx context.Context, credential iamv1.Secret, reference string, byRequest bool) (iamv1.TOTPEnrollment, error) {
	if iamv1.ValidateID("enrollmentReference", reference) != nil {
		return iamv1.TOTPEnrollment{}, ErrInvalidArgument
	}
	var result iamv1.TOTPEnrollment
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if byRequest {
			result, err = tx.ReadTOTPEnrollmentByRequest(ctx, subject.Subject.Session, reference)
		} else {
			result, err = tx.ReadTOTPEnrollment(ctx, subject.Subject.Session, reference)
		}
		return err
	})
	if err != nil {
		return iamv1.TOTPEnrollment{}, err
	}
	if iamv1.ValidateTOTPEnrollment(result) != nil || (byRequest && result.RequestID != reference) || (!byRequest && result.ID != reference) {
		return iamv1.TOTPEnrollment{}, ErrUnavailable
	}
	return result, nil
}

func (service *Authority) CancelTOTPEnrollment(ctx context.Context, credential iamv1.Secret, id string) (iamv1.TOTPEnrollment, error) {
	if iamv1.ValidateID("enrollmentId", id) != nil {
		return iamv1.TOTPEnrollment{}, ErrInvalidArgument
	}
	var result iamv1.TOTPEnrollment
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		result, err = tx.CancelTOTPEnrollment(ctx, subject.Subject.Session, id)
		return err
	})
	if err != nil {
		return iamv1.TOTPEnrollment{}, err
	}
	if iamv1.ValidateTOTPEnrollment(result) != nil || result.ID != id || (result.State != "CANCELLED" && result.State != "EXPIRED") {
		return iamv1.TOTPEnrollment{}, ErrUnavailable
	}
	return result, nil
}

func (service *Authority) StartTOTPEnrollment(ctx context.Context, credential iamv1.Secret, request iamv1.StartTOTPEnrollmentRequest) (iamv1.StartTOTPEnrollmentResponse, error) {
	if iamv1.ValidateStartTOTPEnrollmentRequest(request) != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrInvalidArgument
	}
	if service == nil || service.totpSeeds == nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	if err := service.acquirePasswordWork(ctx); err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	defer service.releasePasswordWork()
	attemptID, err := service.config.NewID("password-attempt")
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	var attempt PasswordAttempt
	var admitted bool
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		// Missing enrollment prerequisites are not a bad login. Check them
		// before reserving password work; the effect function still locks and
		// rechecks the verified contact in the final transaction.
		contact, err := tx.ReadNotificationContact(ctx, notificationSubject(subject))
		if err != nil {
			return err
		}
		if iamv1.ValidateNotificationContact(contact) != nil {
			return ErrUnavailable
		}
		if contact.State != "VERIFIED" {
			return ErrForbidden
		}
		intent, err := digestSanitized("totp-enrollment-password", struct {
			SessionID              iamv1.SessionID
			RequestID              string
			ExpectedFactorRevision uint64
		}{subject.Subject.Session.ID, request.RequestID, request.ExpectedFactorRevision})
		if err != nil {
			return err
		}
		attempt, admitted, err = tx.ReservePasswordAttempt(ctx, PasswordAttemptRequest{ID: attemptID,
			AccountID: subject.Subject.Organization.ID, UserID: subject.Subject.Principal.ID, SessionID: subject.Subject.Session.ID,
			Purpose: PasswordAttemptTOTPEnrollment, IntentDigest: intent})
		return err
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	if err := service.verifyReservedPassword(ctx, request.Password, attempt, admitted); err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	// Reserve the identity and seal exactly once outside the retriable final
	// transaction. A retry must not re-encrypt under the same factor/key identity.
	id, err := service.config.NewID("totp-factor")
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	seed, err := service.credentials.IssueTOTPSeed()
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	scope := authority.TOTPSeedScope{Installation: service.totp.Scope, AccountID: attempt.AccountID, UserID: attempt.PrincipalID, FactorID: id}
	sealed, err := service.totpSeeds.Seal(scope, seed)
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	defer clear(sealed.Nonce)
	defer clear(sealed.Ciphertext)
	uri, err := totpProvisioningURI(attempt.AccountID, attempt.PrincipalID, seed)
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	var result TOTPEnrollmentStartResult
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		result = TOTPEnrollmentStartResult{}
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if subject.Subject.Organization.ID != attempt.AccountID || subject.Subject.Principal.ID != attempt.PrincipalID ||
			subject.Subject.Session.ID != attempt.SessionID || subject.CredentialGeneration != attempt.CredentialGeneration || attempt.Purpose != PasswordAttemptTOTPEnrollment {
			return ErrUnauthenticated
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		result, err = tx.StartTOTPEnrollment(ctx, TOTPEnrollmentStart{Attempt: attempt, RequestID: request.RequestID, FactorID: id,
			ExpectedRevision: request.ExpectedFactorRevision, Scope: scope.Installation, Sealed: sealed})
		return err
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	response := iamv1.StartTOTPEnrollmentResponse{Outcome: result.Outcome, Enrollment: result.Enrollment}
	if result.Outcome == "APPLIED" {
		if result.Enrollment.ID != id {
			return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
		}
		response.Provisioning = &iamv1.TOTPProvisioning{Seed: seed, URI: uri}
	}
	if result.Enrollment.RequestID != request.RequestID || result.Enrollment.FactorRevision != request.ExpectedFactorRevision || iamv1.ValidateStartTOTPEnrollmentResponse(response) != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	return response, nil
}

func (service *Authority) ConfirmTOTPEnrollment(ctx context.Context, credential iamv1.Secret, id string, request iamv1.ConfirmTOTPEnrollmentRequest) (iamv1.ConfirmTOTPEnrollmentResponse, error) {
	if iamv1.ValidateID("enrollmentId", id) != nil || iamv1.ValidateConfirmTOTPEnrollmentRequest(request) != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrInvalidArgument
	}
	if service == nil || service.totpSeeds == nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	attemptID, err := service.config.NewID("totp-attempt")
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	var attempt TOTPAttempt
	var admitted bool
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		attempt, admitted, err = tx.ReserveTOTPAttempt(ctx, TOTPAttempt{AccountID: subject.Subject.Organization.ID,
			UserID: subject.Subject.Principal.ID, SessionID: subject.Subject.Session.ID, ReferenceID: id, Purpose: "ENROLLMENT", ID: attemptID})
		return err
	})
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, err
	}
	if !admitted {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnauthenticated
	}
	batchID, err := service.config.NewID("recovery-batch")
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	codes := make([]iamv1.Secret, 10)
	verifiers := make([]MFARecoveryCodeVerifier, 10)
	for i := range codes {
		codeID, err := service.config.NewID("recovery-code")
		if err != nil {
			return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
		}
		code, err := service.credentials.IssueMFARecoveryCode()
		if err != nil {
			return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
		}
		digest, err := authority.DigestMFARecoveryCode(authority.MFARecoveryCodeScope{InstallationID: service.totp.Scope.InstallationID,
			AccountID: attempt.AccountID, UserID: attempt.UserID, BatchID: batchID, CodeID: codeID}, code)
		if err != nil {
			return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
		}
		codes[i], verifiers[i] = code, MFARecoveryCodeVerifier{ID: codeID, VerificationDigest: digest}
	}
	eventID, err := service.config.NewID("event")
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	notificationID, err := service.config.NewID("notification")
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	digest, err := digestSanitized("totp-enrollment-confirm", struct{ EnrollmentID, RequestID string }{id, request.RequestID})
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, err
	}
	var result iamv1.TOTPEnrollment
	rejected := false
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		rejected, result = false, iamv1.TOTPEnrollment{}
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if subject.Subject.Organization.ID != attempt.AccountID || subject.Subject.Principal.ID != attempt.UserID || subject.Subject.Session.ID != attempt.SessionID {
			return ErrUnauthenticated
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		step, mustChangePassword, err := service.verifyReservedTOTP(ctx, tx, attempt, request.Code)
		if errors.Is(err, authority.ErrTOTPRejected) {
			rejected = true
			return tx.RejectTOTPAttempt(ctx, attempt)
		}
		if err != nil {
			return err
		}
		if mustChangePassword {
			return ErrUnauthenticated
		}
		now, err := transactionTime(ctx, tx)
		if err != nil {
			return err
		}
		event, err := newAuditEvent(eventID, attempt.AccountID, "", auditv1.ActorReference{Type: auditv1.ActorUser, ID: auditv1.ActorID(attempt.UserID)},
			auditv1.ActionIAMAuthenticatorBound, auditv1.TargetReference{Kind: auditv1.TargetPrincipal, ID: string(attempt.UserID)}, auditv1.ResultSucceeded,
			"", digest, request.RequestID, request.RequestID, now)
		if err != nil {
			return err
		}
		result, err = tx.ConfirmTOTPEnrollment(ctx, TOTPEnrollmentConfirmation{Attempt: attempt, VerifiedStep: step, BatchID: batchID,
			NotificationID: notificationID, Codes: verifiers, AuditEvent: event})
		return err
	})
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, err
	}
	if rejected {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnauthenticated
	}
	response := iamv1.ConfirmTOTPEnrollmentResponse{Enrollment: result, NextStep: "REAUTHENTICATE", RecoveryCodes: codes}
	if result.ID != id || iamv1.ValidateConfirmTOTPEnrollmentResponse(response) != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	return response, nil
}
