package identityaccess

import (
	"context"
	"errors"
	"net/url"

	auditv1 "github.com/xiak/matrix/api/audit/v1"
	iamv1 "github.com/xiak/matrix/api/iam/v1"
	"github.com/xiak/matrix/app/service/iam/internal/authority"
)

var ErrTOTPEnrollmentNotFound = errors.New("TOTP enrollment was not found")

// The seed was generated by the fixed authority primitive, not caller input.
// This wire content is for local provisioning only, never a redirect or an
// external QR request. Stable IDs distinguish equal login names.
func totpProvisioningURI(account iamv1.AccountID, user iamv1.PrincipalID, seed iamv1.Secret) (iamv1.Secret, error) {
	encoded := seed.CopyBytes()
	defer clear(encoded)
	values := url.Values{"secret": {string(encoded)}, "issuer": {"MATRIX"}, "algorithm": {"SHA1"}, "digits": {"6"}, "period": {"30"}}
	uri := url.URL{Scheme: "otpauth", Host: "totp", Path: "/MATRIX:" + string(account) + ":" + string(user), RawQuery: values.Encode()}
	return iamv1.NewSecret(uri.String())
}

// Enrollment owns a pending seed and its irreversible confirmation, not a
// second identity or a generic command/receipt mechanism.
type TOTPEnrollmentStart struct {
	Attempt             PasswordAttempt
	Challenge           AuthenticationChallengeCredential
	IntentDigest        string
	RequestID, FactorID string
	ExpectedRevision    uint64
	Scope               iamv1.TOTPWrappingScope
	Sealed              authority.SealedTOTPSeed
}

type TOTPEnrollmentStartResult struct {
	Outcome    string               `json:"outcome"`
	Enrollment iamv1.TOTPEnrollment `json:"enrollment"`
}

// Replacement prepares a new factor under an exact same-Session operation
// proof. It never turns a password-only enrollment into replacement authority.
type TOTPReplacementStart struct {
	Session  iamv1.Session
	Request  iamv1.StartTOTPReplacementRequest
	FactorID string
	Scope    iamv1.TOTPWrappingScope
	Sealed   authority.SealedTOTPSeed
}

// The generation is private evidence for first-contact custody. The public
// observation remains a restricted ceremony, not a Session or a new permit.
type EnrollmentChallengeInspection struct {
	State                iamv1.EnrollmentChallengeState `json:"state"`
	CredentialGeneration uint64                         `json:"credentialGeneration"`
}

func (service *Authority) InspectEnrollmentChallenge(ctx context.Context, id string, request iamv1.InspectEnrollmentChallengeRequest) (iamv1.EnrollmentChallengeState, error) {
	if iamv1.ValidateID("challengeId", id) != nil || iamv1.ValidateInspectEnrollmentChallengeRequest(request) != nil {
		return iamv1.EnrollmentChallengeState{}, ErrInvalidArgument
	}
	var result EnrollmentChallengeInspection
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		identity, err := service.authenticateChallenge(ctx, tx, id, request.ChallengeCredential)
		if err != nil {
			return err
		}
		result, err = readEnrollmentChallenge(ctx, tx, identity)
		return err
	})
	if err != nil {
		return iamv1.EnrollmentChallengeState{}, err
	}
	return result.State, nil
}

func readEnrollmentChallenge(ctx context.Context, tx Transaction, identity AuthenticationChallengeCredential) (EnrollmentChallengeInspection, error) {
	if identity.Purpose != "ENROLLMENT" || (identity.NextStep != "PASSWORD_CHANGE" && identity.NextStep != "ENROLLMENT") {
		return EnrollmentChallengeInspection{}, ErrUnauthenticated
	}
	result, err := tx.ReadEnrollmentChallenge(ctx, identity)
	if err != nil {
		return EnrollmentChallengeInspection{}, err
	}
	if result.CredentialGeneration == 0 || result.CredentialGeneration > 9007199254740991 ||
		iamv1.ValidateEnrollmentChallengeState(result.State) != nil || result.State.Challenge.ID != identity.ID ||
		result.State.Challenge.Purpose != identity.Purpose || result.State.Challenge.NextStep != identity.NextStep ||
		(result.State.NotificationContact != nil && (result.State.NotificationContact.AccountID != identity.AccountID ||
			result.State.NotificationContact.UserID != identity.UserID)) {
		return EnrollmentChallengeInspection{}, ErrUnavailable
	}
	return result, nil
}

type MFARecoveryCodeVerifier struct {
	ID                 string `json:"id"`
	VerificationDigest string `json:"verificationDigest"`
}

type TOTPBindingConfirmation struct {
	Attempt                 TOTPAttempt
	VerifiedStep            int64
	BatchID, NotificationID string
	Codes                   []MFARecoveryCodeVerifier
	AuditEvent              auditv1.Event
}

func (service *Authority) totpSession(ctx context.Context, tx Transaction, credential iamv1.Secret) (SessionCredential, error) {
	now, err := transactionTime(ctx, tx)
	if err != nil {
		return SessionCredential{}, err
	}
	subject, err := service.authenticateSession(ctx, tx, credential, now)
	if err != nil {
		return SessionCredential{}, err
	}
	if subject.Subject.Principal.MustChangePassword {
		return SessionCredential{}, ErrForbidden
	}
	return subject, nil
}

func (service *Authority) AuthenticatorState(ctx context.Context, credential iamv1.Secret) (iamv1.AuthenticatorState, error) {
	var result iamv1.AuthenticatorState
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		result, err = tx.ReadAuthenticatorState(ctx, subject.Subject.Session)
		return err
	})
	if err != nil {
		return iamv1.AuthenticatorState{}, err
	}
	if iamv1.ValidateAuthenticatorState(result) != nil {
		return iamv1.AuthenticatorState{}, ErrUnavailable
	}
	return result, nil
}

func (service *Authority) TOTPEnrollment(ctx context.Context, credential iamv1.Secret, id string) (iamv1.TOTPEnrollment, error) {
	return service.readEnrollment(ctx, credential, id, false)
}

func (service *Authority) TOTPEnrollmentByRequest(ctx context.Context, credential iamv1.Secret, requestID string) (iamv1.TOTPEnrollment, error) {
	return service.readEnrollment(ctx, credential, requestID, true)
}

func (service *Authority) readEnrollment(ctx context.Context, credential iamv1.Secret, reference string, byRequest bool) (iamv1.TOTPEnrollment, error) {
	if iamv1.ValidateID("enrollmentReference", reference) != nil {
		return iamv1.TOTPEnrollment{}, ErrInvalidArgument
	}
	var result iamv1.TOTPEnrollment
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if byRequest {
			result, err = tx.ReadTOTPEnrollmentByRequest(ctx, subject.Subject.Session, reference)
		} else {
			result, err = tx.ReadTOTPEnrollment(ctx, subject.Subject.Session, reference)
		}
		return err
	})
	if err != nil {
		return iamv1.TOTPEnrollment{}, err
	}
	if iamv1.ValidateTOTPEnrollment(result) != nil || (byRequest && result.RequestID != reference) || (!byRequest && result.ID != reference) {
		return iamv1.TOTPEnrollment{}, ErrUnavailable
	}
	return result, nil
}

func (service *Authority) CancelTOTPEnrollment(ctx context.Context, credential iamv1.Secret, id string) (iamv1.TOTPEnrollment, error) {
	if iamv1.ValidateID("enrollmentId", id) != nil {
		return iamv1.TOTPEnrollment{}, ErrInvalidArgument
	}
	var result iamv1.TOTPEnrollment
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		result, err = tx.CancelTOTPEnrollment(ctx, subject.Subject.Session, id)
		return err
	})
	if err != nil {
		return iamv1.TOTPEnrollment{}, err
	}
	if iamv1.ValidateTOTPEnrollment(result) != nil || result.ID != id || (result.State != "CANCELLED" && result.State != "EXPIRED") {
		return iamv1.TOTPEnrollment{}, ErrUnavailable
	}
	return result, nil
}

func (service *Authority) StartTOTPEnrollment(ctx context.Context, credential iamv1.Secret, request iamv1.StartTOTPEnrollmentRequest) (iamv1.StartTOTPEnrollmentResponse, error) {
	if iamv1.ValidateStartTOTPEnrollmentRequest(request) != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrInvalidArgument
	}
	if service == nil || service.totpSeeds == nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	if err := service.acquirePasswordWork(ctx); err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	defer service.releasePasswordWork()
	attemptID, err := service.config.NewID("password-attempt")
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	var attempt PasswordAttempt
	var admitted bool
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		// Missing enrollment prerequisites are not a bad login. Check them
		// before reserving password work; the effect function still locks and
		// rechecks the verified contact in the final transaction.
		contact, err := tx.ReadNotificationContact(ctx, notificationSubject(subject))
		if err != nil {
			return err
		}
		if iamv1.ValidateNotificationContact(contact) != nil {
			return ErrUnavailable
		}
		if contact.State != "VERIFIED" {
			return ErrForbidden
		}
		intent, err := digestSanitized("totp-enrollment-password", struct {
			SessionID              iamv1.SessionID
			RequestID              string
			ExpectedFactorRevision uint64
		}{subject.Subject.Session.ID, request.RequestID, request.ExpectedFactorRevision})
		if err != nil {
			return err
		}
		attempt, admitted, err = tx.ReservePasswordAttempt(ctx, PasswordAttemptRequest{ID: attemptID,
			AccountID: subject.Subject.Organization.ID, UserID: subject.Subject.Principal.ID, SessionID: subject.Subject.Session.ID,
			Purpose: PasswordAttemptTOTPEnrollment, IntentDigest: intent})
		return err
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	if err := service.verifyReservedPassword(ctx, request.Password, attempt, admitted); err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	// Reserve the identity and seal exactly once outside the retriable final
	// transaction. A retry must not re-encrypt under the same factor/key identity.
	change, provisioning, err := service.prepareTOTPEnrollment(attempt.AccountID, attempt.PrincipalID)
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	defer clear(change.Sealed.Nonce)
	defer clear(change.Sealed.Ciphertext)
	change.Attempt, change.IntentDigest = attempt, attempt.IntentDigest
	change.RequestID, change.ExpectedRevision = request.RequestID, request.ExpectedFactorRevision
	var result TOTPEnrollmentStartResult
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		result = TOTPEnrollmentStartResult{}
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if subject.Subject.Organization.ID != attempt.AccountID || subject.Subject.Principal.ID != attempt.PrincipalID ||
			subject.Subject.Session.ID != attempt.SessionID || subject.CredentialGeneration != attempt.CredentialGeneration || attempt.Purpose != PasswordAttemptTOTPEnrollment {
			return ErrUnauthenticated
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		result, err = tx.StartTOTPEnrollment(ctx, change)
		return err
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	return enrollmentStartResponse(change, "INITIAL", provisioning, result)
}

func (service *Authority) StartTOTPReplacement(ctx context.Context, credential iamv1.Secret, request iamv1.StartTOTPReplacementRequest) (iamv1.StartTOTPEnrollmentResponse, error) {
	if iamv1.ValidateStartTOTPReplacementRequest(request) != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrInvalidArgument
	}
	if service == nil || service.totpSeeds == nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	var original SessionCredential
	var proof iamv1.StepUp
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		var err error
		original, err = service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if err := service.checkTOTPCustody(ctx, tx); err != nil {
			return err
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		proof, err = tx.ReadStepUpByRequest(ctx, original.Subject.Session, request.RequestID)
		if err != nil {
			return err
		}
		if iamv1.ValidateStepUp(proof) != nil {
			return ErrUnavailable
		}
		// CONSUMED is only a candidate for metadata replay. The effect port
		// must find the original factor; it cannot consume this proof again.
		if proof.ID != request.StepUpID || proof.RequestID != request.RequestID || proof.Operation != iamv1.StepUpReplaceTOTP ||
			proof.ExpectedFactorRevision != request.ExpectedFactorRevision || (proof.State != "PROVED" && proof.State != "CONSUMED") {
			return ErrConflict
		}
		return nil
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	// Seal once outside the retriable transaction, just as for first binding.
	change, provisioning, err := service.prepareTOTPEnrollment(original.Subject.Organization.ID, original.Subject.Principal.ID)
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	defer clear(change.Sealed.Nonce)
	defer clear(change.Sealed.Ciphertext)
	change.RequestID, change.ExpectedRevision = request.RequestID, request.ExpectedFactorRevision
	var response iamv1.StartTOTPEnrollmentResponse
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		response = iamv1.StartTOTPEnrollmentResponse{}
		current, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return err
		}
		if current.Subject.Organization.ID != original.Subject.Organization.ID || current.Subject.Principal.ID != original.Subject.Principal.ID ||
			current.Subject.Session.ID != original.Subject.Session.ID || current.CredentialGeneration != original.CredentialGeneration {
			return ErrUnauthenticated
		}
		if err := service.checkTOTPCustody(ctx, tx); err != nil {
			return err
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return err
		}
		result, err := tx.StartTOTPReplacement(ctx, TOTPReplacementStart{Session: current.Subject.Session, Request: request,
			FactorID: change.FactorID, Scope: change.Scope, Sealed: change.Sealed})
		if err != nil {
			return err
		}
		// Never renew the original proof deadline or expose material from an
		// unrelated factor, even if the returned metadata is otherwise valid.
		if !result.Enrollment.ExpiresAt.Equal(proof.ExpiresAt) || (proof.State == "CONSUMED" && result.Outcome != "EQUAL_REPLAY") {
			return ErrUnavailable
		}
		response, err = enrollmentStartResponse(change, "REPLACEMENT", provisioning, result)
		return err
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	return response, nil
}

func (service *Authority) StartChallengeTOTPEnrollment(ctx context.Context, id string, request iamv1.StartChallengeTOTPEnrollmentRequest) (iamv1.StartTOTPEnrollmentResponse, error) {
	if iamv1.ValidateID("challengeId", id) != nil || iamv1.ValidateStartChallengeTOTPEnrollmentRequest(request) != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrInvalidArgument
	}
	if service == nil || service.totpSeeds == nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	var identity AuthenticationChallengeCredential
	var inspection EnrollmentChallengeInspection
	err := service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		var err error
		identity, inspection, err = service.initialTOTPEnrollment(ctx, tx, id, request.ChallengeCredential)
		return err
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	change, provisioning, err := service.prepareTOTPEnrollment(identity.AccountID, identity.UserID)
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	defer clear(change.Sealed.Nonce)
	defer clear(change.Sealed.Ciphertext)
	change.Challenge, change.RequestID, change.ExpectedRevision = identity, request.RequestID, 1
	change.IntentDigest, err = digestSanitized("initial-totp-enrollment", struct{ ChallengeID, RequestID string }{id, request.RequestID})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	var result TOTPEnrollmentStartResult
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		current, observed, err := service.initialTOTPEnrollment(ctx, tx, id, request.ChallengeCredential)
		if err != nil {
			return err
		}
		if current != identity || observed.CredentialGeneration != inspection.CredentialGeneration || !observed.State.Challenge.ExpiresAt.Equal(inspection.State.Challenge.ExpiresAt) {
			return ErrUnauthenticated
		}
		result, err = tx.StartTOTPEnrollment(ctx, change)
		return err
	})
	if err != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, err
	}
	if !result.Enrollment.ExpiresAt.Equal(inspection.State.Challenge.ExpiresAt) {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	return enrollmentStartResponse(change, "INITIAL", provisioning, result)
}

func (service *Authority) initialTOTPEnrollment(ctx context.Context, tx Transaction, id string, credential iamv1.Secret) (AuthenticationChallengeCredential, EnrollmentChallengeInspection, error) {
	identity, err := service.authenticateChallenge(ctx, tx, id, credential)
	if err != nil {
		return AuthenticationChallengeCredential{}, EnrollmentChallengeInspection{}, err
	}
	if identity.Purpose != "ENROLLMENT" || identity.NextStep != "ENROLLMENT" {
		return AuthenticationChallengeCredential{}, EnrollmentChallengeInspection{}, ErrUnauthenticated
	}
	inspection, err := readEnrollmentChallenge(ctx, tx, identity)
	if err != nil {
		return AuthenticationChallengeCredential{}, EnrollmentChallengeInspection{}, err
	}
	if inspection.State.NotificationContact.State != "VERIFIED" {
		return AuthenticationChallengeCredential{}, EnrollmentChallengeInspection{}, ErrForbidden
	}
	if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
		return AuthenticationChallengeCredential{}, EnrollmentChallengeInspection{}, err
	}
	return identity, inspection, nil
}

// One seed and ciphertext per proposed factor, outside retriable transactions.
// An equal replay returns the stored metadata without a second secret display.
func (service *Authority) prepareTOTPEnrollment(account iamv1.AccountID, user iamv1.PrincipalID) (TOTPEnrollmentStart, iamv1.TOTPProvisioning, error) {
	id, err := service.config.NewID("totp-factor")
	if err != nil {
		return TOTPEnrollmentStart{}, iamv1.TOTPProvisioning{}, ErrUnavailable
	}
	seed, err := service.credentials.IssueTOTPSeed()
	if err != nil {
		return TOTPEnrollmentStart{}, iamv1.TOTPProvisioning{}, ErrUnavailable
	}
	scope := authority.TOTPSeedScope{Installation: service.totp.Scope, AccountID: account, UserID: user, FactorID: id}
	sealed, err := service.totpSeeds.Seal(scope, seed)
	if err != nil {
		return TOTPEnrollmentStart{}, iamv1.TOTPProvisioning{}, ErrUnavailable
	}
	uri, err := totpProvisioningURI(account, user, seed)
	if err != nil {
		clear(sealed.Nonce)
		clear(sealed.Ciphertext)
		return TOTPEnrollmentStart{}, iamv1.TOTPProvisioning{}, ErrUnavailable
	}
	return TOTPEnrollmentStart{FactorID: id, Scope: scope.Installation, Sealed: sealed}, iamv1.TOTPProvisioning{Seed: seed, URI: uri}, nil
}

func enrollmentStartResponse(change TOTPEnrollmentStart, purpose string, provisioning iamv1.TOTPProvisioning, result TOTPEnrollmentStartResult) (iamv1.StartTOTPEnrollmentResponse, error) {
	response := iamv1.StartTOTPEnrollmentResponse{Outcome: result.Outcome, Enrollment: result.Enrollment}
	if result.Outcome == "APPLIED" {
		if result.Enrollment.ID != change.FactorID {
			return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
		}
		response.Provisioning = &provisioning
	}
	if result.Enrollment.Purpose != purpose || result.Enrollment.RequestID != change.RequestID || result.Enrollment.FactorRevision != change.ExpectedRevision || iamv1.ValidateStartTOTPEnrollmentResponse(response) != nil {
		return iamv1.StartTOTPEnrollmentResponse{}, ErrUnavailable
	}
	return response, nil
}

func (service *Authority) ConfirmTOTPEnrollment(ctx context.Context, credential iamv1.Secret, id string, request iamv1.ConfirmTOTPEnrollmentRequest) (iamv1.ConfirmTOTPEnrollmentResponse, error) {
	if iamv1.ValidateID("enrollmentId", id) != nil || iamv1.ValidateConfirmTOTPEnrollmentRequest(request) != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrInvalidArgument
	}
	return service.confirmTOTPEnrollment(ctx, request.RequestID, request.Code, func(ctx context.Context, tx Transaction) (TOTPAttempt, string, error) {
		subject, err := service.totpSession(ctx, tx, credential)
		if err != nil {
			return TOTPAttempt{}, "", err
		}
		if err := service.checkEmailVerificationCustody(ctx, tx); err != nil {
			return TOTPAttempt{}, "", err
		}
		enrollment, err := tx.ReadTOTPEnrollment(ctx, subject.Subject.Session, id)
		if err != nil {
			return TOTPAttempt{}, "", err
		}
		if iamv1.ValidateTOTPEnrollment(enrollment) != nil || enrollment.ID != id {
			return TOTPAttempt{}, "", ErrUnavailable
		}
		purpose := "ENROLLMENT"
		if enrollment.Purpose == "REPLACEMENT" {
			purpose = "REPLACEMENT"
		}
		return TOTPAttempt{AccountID: subject.Subject.Organization.ID, UserID: subject.Subject.Principal.ID,
			SessionID: subject.Subject.Session.ID, ReferenceID: id, Purpose: purpose}, id, nil
	})
}

func (service *Authority) ConfirmChallengeTOTPEnrollment(ctx context.Context, id string, request iamv1.VerifyAuthenticationChallengeRequest) (iamv1.ConfirmTOTPEnrollmentResponse, error) {
	if iamv1.ValidateID("challengeId", id) != nil || iamv1.ValidateVerifyAuthenticationChallengeRequest(request) != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrInvalidArgument
	}
	return service.confirmTOTPEnrollment(ctx, request.RequestID, request.Code, func(ctx context.Context, tx Transaction) (TOTPAttempt, string, error) {
		identity, inspection, err := service.initialTOTPEnrollment(ctx, tx, id, request.ChallengeCredential)
		if err != nil {
			return TOTPAttempt{}, "", err
		}
		if inspection.State.Enrollment == nil {
			return TOTPAttempt{}, "", ErrConflict
		}
		return TOTPAttempt{AccountID: identity.AccountID, UserID: identity.UserID, ReferenceID: id, Purpose: "INITIAL_ENROLLMENT"}, inspection.State.Enrollment.ID, nil
	})
}

func (service *Authority) confirmTOTPEnrollment(ctx context.Context, requestID string, code iamv1.Secret,
	authenticate func(context.Context, Transaction) (TOTPAttempt, string, error)) (iamv1.ConfirmTOTPEnrollmentResponse, error) {
	if service == nil || service.totpSeeds == nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	attemptID, err := service.config.NewID("totp-attempt")
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	var attempt TOTPAttempt
	var factorID string
	var admitted bool
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		var err error
		attempt, factorID, err = authenticate(ctx, tx)
		if err != nil {
			return err
		}
		attempt.ID = attemptID
		attempt, admitted, err = tx.ReserveTOTPAttempt(ctx, attempt)
		return err
	})
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, err
	}
	if !admitted {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnauthenticated
	}
	batchID, codes, verifiers, err := service.newRecoveryBatch(attempt.AccountID, attempt.UserID)
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, err
	}
	eventID, err := service.config.NewID("event")
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	notificationID, err := service.config.NewID("notification")
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	digest, err := digestSanitized("totp-enrollment-confirm", struct{ EnrollmentID, RequestID string }{factorID, requestID})
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, err
	}
	var result iamv1.TOTPEnrollment
	rejected := false
	err = service.withinTransaction(ctx, func(ctx context.Context, tx Transaction) error {
		rejected, result = false, iamv1.TOTPEnrollment{}
		current, currentFactor, err := authenticate(ctx, tx)
		if err != nil {
			return err
		}
		if current.AccountID != attempt.AccountID || current.UserID != attempt.UserID || current.SessionID != attempt.SessionID ||
			current.Purpose != attempt.Purpose || current.ReferenceID != attempt.ReferenceID || currentFactor != factorID {
			return ErrUnauthenticated
		}
		step, mustChangePassword, err := service.verifyReservedTOTP(ctx, tx, attempt, code)
		if errors.Is(err, authority.ErrTOTPRejected) {
			rejected = true
			return tx.RejectTOTPAttempt(ctx, attempt)
		}
		if err != nil {
			return err
		}
		if mustChangePassword {
			return ErrUnauthenticated
		}
		now, err := transactionTime(ctx, tx)
		if err != nil {
			return err
		}
		action := auditv1.ActionIAMAuthenticatorBound
		if attempt.Purpose == "REPLACEMENT" {
			action = auditv1.ActionIAMAuthenticatorReplaced
		}
		event, err := newAuditEvent(eventID, attempt.AccountID, "", auditv1.ActorReference{Type: auditv1.ActorUser, ID: auditv1.ActorID(attempt.UserID)},
			action, auditv1.TargetReference{Kind: auditv1.TargetPrincipal, ID: string(attempt.UserID)}, auditv1.ResultSucceeded,
			"", digest, requestID, requestID, now)
		if err != nil {
			return err
		}
		result, err = tx.ConfirmTOTPEnrollment(ctx, TOTPBindingConfirmation{Attempt: attempt, VerifiedStep: step, BatchID: batchID,
			NotificationID: notificationID, Codes: verifiers, AuditEvent: event})
		if err == nil && ((result.Purpose == "REPLACEMENT") != (attempt.Purpose == "REPLACEMENT")) {
			return ErrUnavailable
		}
		return err
	})
	if err != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, err
	}
	if rejected {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnauthenticated
	}
	response := iamv1.ConfirmTOTPEnrollmentResponse{Enrollment: result, NextStep: "REAUTHENTICATE", RecoveryCodes: codes}
	if result.ID != factorID || iamv1.ValidateConfirmTOTPEnrollmentResponse(response) != nil {
		return iamv1.ConfirmTOTPEnrollmentResponse{}, ErrUnavailable
	}
	return response, nil
}
