// Generated from api/devops/v1/openapi.json. Run npm run generate:contracts.
import type { ContractValidators } from "./validation";
import * as compiled from "./devopsValidate";

export type ChangeAction = "OPENED" | "REOPENED" | "UPDATED";
export type ChangeIdentity = { "action": ChangeAction; "headCommit": string; "number": number; "trustedBaseCommit": string; };
export type CreateDevOpsProjectRequest = { "id": ResourceID; "name": string; };
export type CreatePipelineRequest = { "draft": PipelineDraftSpec; "id": ResourceID; "name": string; "projectId": ResourceID; };
export type CreateRepositoryBindingRequest = { "id": ResourceID; "name": string; "projectId": ResourceID; "spec": RepositoryBindingSpec; };
export type CreateSourceConnectionRequest = { "id": ResourceID; "name": string; "spec": SourceConnectionSpec; };
export type DependencyEgressPolicy = "NONE";
export type DevOpsProject = { "apiVersion": "devops.matrix.xiak.com/v1"; "kind": "DevOpsProject"; "metadata": ResourceMetadata; };
export type Pipeline = { "activeRevision"?: PipelineRevisionReference; "apiVersion": "devops.matrix.xiak.com/v1"; "draft": PipelineDraft; "kind": "Pipeline"; "metadata": ResourceMetadata; "projectId": ResourceID; };
export type PipelineActivation = { "apiVersion": "devops.matrix.xiak.com/v1"; "kind": "PipelineActivation"; "pipeline": Pipeline; "revision": PipelineRevision; };
export type PipelineDraft = { "contentDigest": string; "spec": PipelineDraftSpec; };
export type PipelineDraftSpec = { "dependencyEgress": DependencyEgressPolicy; "reporterPolicy": ReporterPolicy; "repositoryBindingId": ResourceID; "triggerPolicy": TriggerPolicy; "verificationProfile": VerificationProfile; };
export type PipelineRevision = { "activatedAt": Timestamp; "activatedBy": SubjectRef; "apiVersion": "devops.matrix.xiak.com/v1"; "contentDigest": string; "id": ResourceID; "kind": "PipelineRevision"; "pipelineId": ResourceID; "projectId": ResourceID; "revision": number; "scope": ResourceScope; "spec": PipelineRevisionSpec; };
export type PipelineRevisionReference = { "contentDigest": string; "id": ResourceID; "revision": number; };
export type PipelineRevisionSpec = { "dependencyEgress": DependencyEgressPolicy; "executorProfile": "MATRIX_NATIVE_ISOLATED_V1"; "limits": VerificationLimits; "reporterPolicy": ReporterPolicy; "repositoryBindingDigest": string; "repositoryBindingId": ResourceID; "steps": [{ "kind": "GO_TEST"; "ordinal": 1; }, { "kind": "GO_VET"; "ordinal": 2; }]; "toolchainImageDigest": "sha256:07558d5472e9acb5fc5656b485e963602e925e00111b8ad676a804306e711ba3"; "triggerPolicy": TriggerPolicy; "verificationProfile": VerificationProfile; };
export type PipelineRun = { "apiVersion": "devops.matrix.xiak.com/v1"; "createdAt": Timestamp; "id": ResourceID; "input": PipelineRunInput; "inputDigest": string; "kind": "PipelineRun"; "pipelineId": ResourceID; "projectId": ResourceID; "replay"?: PipelineRunReplay; "scope": ResourceScope; "status": PipelineRunStatus; "updatedAt": Timestamp; };
export type PipelineRunInput = { "change": ChangeIdentity; "pipelineRevisionDigest": string; "pipelineRevisionId": ResourceID; "repositoryBindingDigest": string; "repositoryBindingId": ResourceID; "sourceEventDigest": string; "sourceEventId": ResourceID; };
export type PipelineRunLogChunk = { "content": string; "expiresAt": Timestamp; "sequence": number; "step": VerificationStep; };
export type PipelineRunLogPage = { "afterSequence": number; "apiVersion": "devops.matrix.xiak.com/v1"; "chunks": Array<PipelineRunLogChunk>; "hasMore": boolean; "kind": "PipelineRunLogPage"; "nextSequence": number; "readAt": Timestamp; "runId": ResourceID; "truncated": boolean; };
export type PipelineRunReason = "EVENT_ADMITTED" | "COMPLETED" | "SOURCE_UNAVAILABLE" | "COMMIT_MISMATCH" | "EXECUTOR_UNAVAILABLE" | "VERIFICATION_FAILED" | "DEADLINE_EXCEEDED" | "REPORT_UNAVAILABLE" | "REPORT_CONFLICT" | "CANCELLED" | "EXTERNAL_EFFECT_UNCERTAIN" | "RECONCILIATION_EXHAUSTED";
export type PipelineRunReplay = { "commandId": string; "requestedBy": SubjectRef; "sourceRunId": string; };
export type PipelineRunStage = "RECEIVE" | "FETCH" | "VERIFY" | "REPORT";
export type PipelineRunState = "QUEUED" | "FETCHING" | "VERIFYING" | "REPORTING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "RECONCILING" | "MANUAL_INTERVENTION";
export type PipelineRunStatus = ({ "cancellationRequestedAt"?: Timestamp; "completedAt"?: Timestamp; "observedAt": Timestamp; "reason"?: PipelineRunReason; "resourceVersion": number; "stage": PipelineRunStage; "state": PipelineRunState; }) & (unknown) & (unknown) & (unknown) & (unknown) & (unknown) & (unknown) & (unknown) & (unknown) & (unknown);
export type ReporterPolicy = "CHANGE_CHECK_V1";
export type RepositoryBinding = { "apiVersion": "devops.matrix.xiak.com/v1"; "contentDigest": string; "kind": "RepositoryBinding"; "metadata": ResourceMetadata; "projectId": ResourceID; "spec": RepositoryBindingSpec; "status": RepositoryBindingStatus; };
export type RepositoryBindingHealth = "PENDING" | "READY" | "UNAVAILABLE";
export type RepositoryBindingHealthReason = "CONFIGURATION_CHANGED" | "CONNECTION_NOT_READY" | "OBSERVED" | "REPOSITORY_UNAVAILABLE" | "IDENTITY_MISMATCH" | "FETCH_PERMISSION_DENIED" | "REPORT_PERMISSION_DENIED";
export type RepositoryBindingSpec = { "externalRepositoryId": ResourceID; "repositoryPath": string; "sourceConnectionId": ResourceID; "trustedDefaultBranch": string; };
export type RepositoryBindingStatus = ({ "health": RepositoryBindingHealth; "observedAt": Timestamp; "reason": RepositoryBindingHealthReason; }) & (unknown) & (unknown) & (unknown);
export type ResourceID = string;
export type ResourceMetadata = { "createdAt": Timestamp; "id": ResourceID; "name": string; "resourceVersion": number; "scope": ResourceScope; "updatedAt": Timestamp; };
export type ResourceScope = { "tenantId": TenantID; };
export type SourceConnection = { "apiVersion": "devops.matrix.xiak.com/v1"; "kind": "SourceConnection"; "metadata": ResourceMetadata; "spec": SourceConnectionSpec; "status": SourceConnectionStatus; };
export type SourceConnectionHealth = "PENDING" | "READY" | "UNAVAILABLE";
export type SourceConnectionHealthReason = "CONFIGURATION_CHANGED" | "OBSERVED" | "SECRET_UNAVAILABLE" | "PROVIDER_UNAVAILABLE" | "PROVIDER_UNSUPPORTED" | "CREDENTIAL_REJECTED";
export type SourceConnectionSpec = { "adapterId": ResourceID; "endpointOrigin": string; "fetchCredentialRef": ResourceID; "reportCredentialRef": ResourceID; "webhookSecretRef": ResourceID; };
export type SourceConnectionStatus = ({ "health": SourceConnectionHealth; "observedAt": Timestamp; "reason": SourceConnectionHealthReason; }) & (unknown) & (unknown) & (unknown);
export type SubjectKind = "USER" | "SERVICE_ACCOUNT";
export type SubjectRef = { "id": string; "kind": SubjectKind; };
export type TenantID = string;
export type Timestamp = string;
export type TriggerPolicy = "CHANGE";
export type UpdatePipelineDraftRequest = { "draft": PipelineDraftSpec; };
export type VerificationLimits = { "cpuMillis": 2000; "maxLogBytes": 8388608; "memoryBytes": 2147483648; "processLimit": 256; "runTimeoutSeconds": 1200; "stepTimeoutSeconds": 600; "writableBytes": 2147483648; };
export type VerificationProfile = "GO_1_26_OFFLINE_V1";
export type VerificationStep = { "kind": VerificationStepKind; "ordinal": number; };
export type VerificationStepKind = "GO_TEST" | "GO_VET";

export const validators: ContractValidators = compiled;
