// Generated from api/paas/v1/openapi.json. Run npm run generate:contracts.
import type { ContractValidators } from "./validation";
import * as compiled from "./paasValidate";

export type Application = { "apiVersion": "paas.matrix.xiak.com/v1"; "kind": "Application"; "metadata": ResourceMetadata; };
export type ApplicationEndpoint = { "name": Name; "port": number; "protocol": EndpointProtocol; "visibility": EndpointVisibility; };
export type ApplicationRevision = { "apiVersion": "paas.matrix.xiak.com/v1"; "kind": "ApplicationRevision"; "metadata": ResourceMetadata; "spec": ApplicationRevisionSpec; };
export type ApplicationRevisionComponent = { "artifact": ArtifactRef; "endpoints"?: Array<ApplicationEndpoint>; "inputs"?: Array<ComponentInput>; "name": Name; "resources": ResourceRequirements; };
export type ApplicationRevisionSpec = { "applicationId": ID; "components": Array<ApplicationRevisionComponent>; "contentDigest": Digest; "revision": string; };
export type ArtifactKind = "OCI_IMAGE" | "OCI_ARTIFACT" | "RELEASE_BUNDLE";
export type ArtifactRef = { "digest": Digest; "kind": ArtifactKind; "locator": string; };
export type AuthorityKind = "PLATFORM" | "TENANT";
export type ComponentBinding = ({ "configurationRevisionId"?: ID; "name": Name; "secretVersion"?: SecretVersionReference; }) & (({ "secretVersion"?: never; }) | ({ "configurationRevisionId"?: never; }));
export type ComponentInput = ({ "injection": InjectionMode; "kind": InputKind; "name": Name; "required": boolean; }) & (unknown) & (unknown);
export type Configuration = { "apiVersion": "paas.matrix.xiak.com/v1"; "applicationId": ID; "kind": "Configuration"; "metadata": ResourceMetadata; };
export type ConfigurationRevision = { "apiVersion": "paas.matrix.xiak.com/v1"; "kind": "ConfigurationRevision"; "metadata": ResourceMetadata; "spec": ConfigurationRevisionSpec; };
export type ConfigurationRevisionSpec = { "configurationId": ID; "contentDigest": Digest; "values": {  } & Record<string, string>; };
export type CreateApplicationRequest = { "id": ID; "labels"?: Labels; "name": Name; };
export type CreateApplicationRevisionRequest = { "id": ID; "labels"?: Labels; "name": Name; "spec": ApplicationRevisionSpec; };
export type CreateConfigurationRequest = { "applicationId": ID; "id": ID; "labels"?: Labels; "name": Name; };
export type CreateConfigurationRevisionRequest = { "id": ID; "labels"?: Labels; "name": Name; "spec": ConfigurationRevisionSpec; };
export type CreateDeploymentRequest = { "id": ID; "name": Name; "spec": DeploymentSpec; };
export type Deployment = { "apiVersion": "paas.matrix.xiak.com/v1"; "generation": number; "kind": "Deployment"; "metadata": ResourceMetadata; "spec": DeploymentSpec; "status": DeploymentStatus; };
export type DeploymentComponent = { "bindings"?: Array<ComponentBinding>; "name": Name; "replicas": number; };
export type DeploymentDesiredState = "RUNNING" | "STOPPED";
export type DeploymentGeneration = { "apiVersion": "paas.matrix.xiak.com/v1"; "contentDigest": Digest; "createdAt": Timestamp; "createdByOperationId": ID; "deploymentId": ID; "generation": number; "kind": "DeploymentGeneration"; "scope": ResourceScope; "spec": DeploymentSpec; };
export type DeploymentPhase = "PENDING" | "PLACING" | "APPLYING" | "READY" | "DEGRADED" | "FAILED" | "STOPPING" | "STOPPED";
export type DeploymentSpec = { "applicationRevisionId": ID; "components": Array<DeploymentComponent>; "desiredState": DeploymentDesiredState; "placementPolicyId": ID; };
export type DeploymentStatus = { "currentOperationId"?: ID; "observedApplicationRevisionId"?: ID; "observedAt": Timestamp; "observedGeneration": number; "phase": DeploymentPhase; "placementDecisionId"?: ID; "readyComponents": number; };
export type Digest = string;
export type EndpointProtocol = "HTTP" | "GRPC" | "TCP";
export type EndpointVisibility = "PRIVATE" | "PUBLIC";
export type ErrorCode = "INVALID_ARGUMENT" | "UNAUTHENTICATED" | "PERMISSION_DENIED" | "IDENTITY_PROVIDER_UNAVAILABLE" | "NOT_FOUND" | "ALREADY_EXISTS" | "CONFLICT" | "RESOURCE_VERSION_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "UNSCHEDULABLE" | "CAPABILITY_UNSUPPORTED" | "EXECUTION_TARGET_UNAVAILABLE" | "ADAPTER_UNAVAILABLE" | "ADAPTER_REJECTED" | "ADAPTER_OUTCOME_UNKNOWN" | "DEADLINE_EXCEEDED" | "OPERATION_FAILED" | "MANUAL_INTERVENTION_REQUIRED" | "RATE_LIMITED" | "INTERNAL";
export type FieldViolation = { "description": string; "field": string; };
export type ID = string;
export type InjectionMode = "ENV" | "FILE";
export type InputKind = "CONFIGURATION" | "SECRET";
export type Labels = {  } & Record<string, string>;
export type Name = string;
export type Operation = { "action": OperationAction; "apiVersion": "paas.matrix.xiak.com/v1"; "attempt": number; "createdAt": Timestamp; "error"?: Problem; "id": ID; "idempotencyFingerprint": Digest; "kind": "Operation"; "requestDigest": Digest; "requestedBy": SubjectRef; "scope": ResourceScope; "state": OperationState; "target": ResourceRef; "terminalAt"?: Timestamp; "updatedAt": Timestamp; };
export type OperationAction = "CREATE_EXECUTION_POOL" | "REGISTER_EXECUTION_TARGET" | "CREATE_PLACEMENT" | "CREATE_APPLICATION" | "CREATE_CONFIGURATION" | "CREATE_CONFIGURATION_REVISION" | "CREATE_APPLICATION_REVISION" | "DEPLOY" | "UPDATE" | "STOP" | "ROLLBACK";
export type OperationState = "ACCEPTED" | "PLANNING" | "QUEUED" | "EXECUTING" | "VERIFYING" | "RECONCILING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "MANUAL_INTERVENTION";
export type Problem = { "code": ErrorCode; "detail": string; "instance"?: string; "retryable": boolean; "status": number; "title": string; "traceId": ID; "type": string; "violations"?: Array<FieldViolation>; };
export type ResourceMetadata = { "createdAt": Timestamp; "id": ID; "labels"?: Labels; "name": Name; "resourceVersion": number; "scope": ResourceScope; "updatedAt": Timestamp; };
export type ResourceRef = { "id": ID; "kind": string; };
export type ResourceRequirements = { "cpuMillis": number; "memoryBytes": number; };
export type ResourceScope = { "kind": AuthorityKind; "tenantId"?: ID; };
export type RollbackDeploymentRequest = { "sourceGeneration": number; };
export type SecretVersionReference = { "secretId": ID; "version": string; };
export type SubjectRef = { "id": ID; "type": SubjectType; };
export type SubjectType = "USER" | "SERVICE_ACCOUNT" | "AGENT" | "SYSTEM_USER";
export type Timestamp = string;

export const validators: ContractValidators = compiled;
